name = "PairAsPipe"
uuid = "38789a04-2ff8-46a2-8332-e7d8e8ce74aa"
authors = ["Dai ZJ <zhuojia.dai@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
